### ISSUE TITLE
Malformed class name

### ISSUE THREAD

**Issue by umbreak** [mockito/mockito-scala#117]
When using a case class or case object in the following way
```scala
 sealed trait SomeTrait
  object SomeTrait {
    final case object A extends SomeTrait
    final case object B  extends SomeTrait
  }
```
It crashes when the underlying JVM selected is java-8

with the following stack trace

```
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at ru.vyarus.java.generics.resolver.util.TypeToStringUtils.toStringType(TypeToStringUtils.java:42)
	at ru.vyarus.java.generics.resolver.util.TypeToStringUtils.join(TypeToStringUtils.java:189)
	at ru.vyarus.java.generics.resolver.util.TypeToStringUtils.toStringMethod(TypeToStringUtils.java:107)
	at ru.vyarus.java.generics.resolver.context.GenericsContext.method(GenericsContext.java:148)
	at org.mockito.ReflectionUtils$InvocationOnMockOps.$anonfun$resolveWithJavaGenerics$1(ReflectionUtils.scala:56)
	at scala.util.Try$.apply(Try.scala:213)
	at org.mockito.ReflectionUtils$InvocationOnMockOps.resolveWithJavaGenerics(ReflectionUtils.scala:56)
	at org.mockito.ReflectionUtils$InvocationOnMockOps.$anonfun$returnType$1(ReflectionUtils.scala:31)
	at scala.Option.orElse(Option.scala:306)
	at org.mockito.ReflectionUtils$InvocationOnMockOps.returnType(ReflectionUtils.scala:31)
	at org.mockito.stubbing.ReturnsSmartNulls$.$anonfun$apply$1(ReturnsSmartNulls.scala:17)
	at scala.Option.orElse(Option.scala:306)
	at org.mockito.stubbing.ReturnsSmartNulls$.apply(ReturnsSmartNulls.scala:16)
	at org.mockito.stubbing.ReturnsSmartNulls$.apply(ReturnsSmartNulls.scala:12)
	at org.mockito.stubbing.DefaultAnswer.answer(DefaultAnswer.scala:12)
	at org.mockito.stubbing.DefaultAnswer.answer$(DefaultAnswer.scala:12)
	at org.mockito.stubbing.ReturnsSmartNulls$.answer(ReturnsSmartNulls.scala:12)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.ScalaMockHandler.handle(ScalaMockHandler.scala:37)
	at org.mockito.internal.handler.ScalaNullResultGuardian.handle(ScalaNullResultGuardian.scala:10)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:126)
	at ExampleSpec$Client$MockitoMock$56560596.apply(Unknown Source)
```

Changing it to something like this works
```scala
 sealed trait SomeTrait
 final case object A extends SomeTrait
 final case object B  extends SomeTrait
```

You can reproduce it with the following example: https://gist.github.com/umbreak/6c2adaeb67c6488cc7f2438f9459af6f

**Comment by umbreak** [comment]
I don't have the same issue with Java 10

**Comment by ultrasecreth** [comment]
@umbreak Interesting, I'll take a look, thanks for the detailed explanation!

**Comment by ultrasecreth** [comment]
So, it seems to be a bug in how the Scala compiler names the classes, if you just do
```scala
println(Permissions.Allowed.getClass.getSimpleName)
```
it will throw the same exception.
This is due to the algorithm used by the JVM8, the JLS3 "Binary Compatibility" (13.1) says that inner classes names will be formed by the container class name plus $ plus the inner class name `Parent$Inner`, and so in order to get the `Inner` class name, they remove from the string the length of the name of the parent, and then, they manually remove the `$`, now, because the parent here is an `object` its name ends in `$`, and there is no second `$` after it, so when they try to remove `$`, they don't find it and everything blows up.
I'll try to see if I can hack it so it doesn't blow up for us
BTW, JVM 11 uses a diff algorithm, that's why it doesn't fail
