### ISSUE TITLE
Testing a trait while mocking abstract

### ISSUE THREAD

**Issue by melodious** [mockito/mockito-scala#130]
I am trying to test a trait that has concrete and abstract methods. I would like to test the concrete methods and mock the abstract methods. When I do this, I get an exception:

```
An exception or error caused a run to abort: java.lang.Object.concreteMethod(Ljava/lang/Object;)Z 
java.lang.NoSuchMethodError: java.lang.Object.concreteMethod(Ljava/lang/Object;)Z
	at com.verisign.ie.styx.cassandra.tables.TestingTraitsTest.$anonfun$new$1(TestingTraitsTest.scala:21)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
```

Here is example code:

```scala
trait TestingTraits {
  
  def myAbstractMethod(arg:Object): Boolean

  def concreteMethod(arg: Object): Boolean = {
    myAbstractMethod(arg)
  }
}
```
and the test:

```scala
class TestingTraitsTest extends FunSuite with MockitoSugar with GivenWhenThen {

  test("record not in cache, not in database") {
    case class TestRecord()

    val arg = TestRecord()
    val mockTrait = mock[TestingTraits]

    mwhen(mockTrait.myAbstractMethod(arg)).thenReturn(true)


    mwhen(mockTrait.concreteMethod(same(arg))).thenCallRealMethod()
    mockTrait.concreteMethod(arg)

    verify(mockTrait.myAbstractMethod(arg))
  }
}
```

Is there any way to get this working? Thanks!

**Comment by ultrasecreth** [comment]
Hi @melodious, I just ran that code and it works (after I fixed the compile & syntax errors)
What version of Scala and mockito-scala are you using?
Could you please add the imports to the example?

**Comment by melodious** [comment]
Thanks for your response, bbonanno. Your questions lead me to figure out what was wrong since it related to my library configuration. I have it working now. Thanks.
