### ISSUE TITLE
VerifyMacro.wasMacro picked up test class as mocked object

### ISSUE THREAD

**Issue by ChengGit** [mockito/mockito-scala#155]
Hi guys,

I am running this piece of code and hit a runtime error `<my_test_class_name> is not a mock object`, which seems like implicit conversion and macro somehow picked up my test class as T instead of the mocked object.
would you shed some lights on this scenario? 

*stacktrace is here:*
```
Argument passed to verify() is of type EmailUtilImplSpec and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();
org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type EmailUtilImplSpec and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();
	at io.cheng.di.dependencyInversion.EmailUtilImplSpec.$anonfun$new$3(EmailUtilImplSpec.scala:21)
	at io.cheng.di.dependencyInversion.EmailUtilImplSpec.verification(EmailUtilImplSpec.scala:12)
	at io.cheng.di.dependencyInversion.EmailUtilImplSpec.$anonfun$new$2(EmailUtilImplSpec.scala:21)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at org.scalatest.concurrent.SerialExecutionContext.recRunNow(SerialExecutionContext.scala:120)
	at org.scalatest.concurrent.SerialExecutionContext.runNow(SerialExecutionContext.scala:111)
	at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:298)
	at org.scalatest.AsyncFlatSpecLike.runTest(AsyncFlatSpecLike.scala:1706)
	at org.scalatest.AsyncFlatSpecLike.runTest$(AsyncFlatSpecLike.scala:1686)
	at org.scalatest.AsyncFlatSpec.runTest(AsyncFlatSpec.scala:2219)
	at org.scalatest.AsyncFlatSpecLike.$anonfun$runTests$1(AsyncFlatSpecLike.scala:1764)
	at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:437)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:422)
	at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:486)
	at org.scalatest.AsyncSuperEngine.runTestsImpl(AsyncEngine.scala:557)
	at org.scalatest.AsyncFlatSpecLike.runTests(AsyncFlatSpecLike.scala:1764)
	at org.scalatest.AsyncFlatSpecLike.runTests$(AsyncFlatSpecLike.scala:1763)
	at org.scalatest.AsyncFlatSpec.runTests(AsyncFlatSpec.scala:2219)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.AsyncFlatSpec.org$scalatest$AsyncFlatSpecLike$$super$run(AsyncFlatSpec.scala:2219)
	at org.scalatest.AsyncFlatSpecLike.$anonfun$run$1(AsyncFlatSpecLike.scala:1809)
	at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:627)
	at org.scalatest.AsyncFlatSpecLike.run(AsyncFlatSpecLike.scala:1809)
	at org.scalatest.AsyncFlatSpecLike.run$(AsyncFlatSpecLike.scala:1807)
	at org.scalatest.AsyncFlatSpec.run(AsyncFlatSpec.scala:2219)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```

*And here is the test I am running:*
```scala
package io.cheng.di.dependencyInversion

import io.cheng.di.dependencyInversion.EmailUtil.EmailUtilImpl
import io.cheng.di.model.EmailServerResponse
import io.cheng.di.thridParty.EmailServerClient
import org.mockito.scalatest.AsyncIdiomaticMockito
import org.scalatest.{AsyncFlatSpec, Matchers}

import scala.concurrent.Future
import scala.language.postfixOps

class EmailUtilImplSpec extends AsyncFlatSpec with Matchers with AsyncIdiomaticMockito{
  val clientMock: EmailServerClient = mock[EmailServerClient]
  val instance = new EmailUtilImpl(clientMock)
  val dummyResponse = EmailServerResponse(200, None)

  it should "call 3rd party client correctly" in {
    clientMock.sendEmail(any) returns Future.successful(dummyResponse)
    instance.sendPredefinedEmail("dummy email").map(
      (response: EmailServerResponse) => {
        clientMock.was(called)
      }
    )
  }
}
```

**Comment by ultrasecreth** [comment]
Your verification is wrong, you need to specify what method you expect to be called, something along the lines of
```scala
clientMock.sendEmail(*) was called
```
Also check out the cats module so you can get rid of the Future ;)

**Comment by ChengGit** [comment]
@bbonanno thanks! I did forget to claim which method to verify! And now it works like a charm!

Hah I love the second piece of suggestion more! yeah I am working on helping team to limit usage reduce hard-coded dependencies, limit usage of mocks down to the edge of our application, and eventually ~hopefully~ moving into mtl style🤣

**Comment by ChengGit** [comment]
I will close this ticket, thanks for your help!
