### ISSUE TITLE
Conflicting versions of ArgumentsProcessor in mockito-core and mockito-scala

### ISSUE THREAD

**Issue by sirmax** [mockito/mockito-scala#18]
`org.mockito.internal.invocation.ArgumentsProcessor` class exists in both `mockito-core` and `mockito-scala` projects with different API.

Since classloading order is unreliable both versions can be loaded. As a result, when `mockito-core`'s version gets loaded first, there will be errors
```
java.lang.NoSuchFieldError: extractors
     at org.mockito.ReflectionUtils$.markMethodsWithLazyArgs(ReflectionUtils.scala:19)
     at org.mockito.MockitoEnhancer.mock(MockitoSugar.scala:122)
     at org.mockito.MockitoEnhancer.mock$(MockitoSugar.scala:119)
```

Please consider moving or renaming `mockito-scala`'s version.

**Comment by bbonanno** [comment]
We rely on the class loader to replace that class for the time being (ugly hack, I know).
mockito-scala already pulls the right version of mockito-core as a transitive dependency, so you shouldn't have to declare it explicitly and that should also solve the class loader issue by making the mockito-scala version of the class the winning one

Please let me know if you have the same issue when only declaring mockito-scala as dependency
BTW, in some other thread somebody mention that scalatest may be also pulling a  mockito-core dependency, I haven't had issues with it, but just in case ensure mockito-scala is declared after scalatest and/or exclude the transitive dependency that scalatest has on mockito

**Comment by bbonanno** [comment]
Well, it seems that it's not consistent, I've created a dummy test project https://github.com/bbonanno/mockito-scala-as-dependency and it works as it is, but then if you add the `mockito-core` dependency, sometimes it works in SBT and not in the IDE and vice-versa depending in what order you put it, something surprising is that for some people it seems to work by putting the `mockito-core` dependency **after** the `mockito-scala` one (specs2 does something similar, so there are some StackOverflow posts about a very similar issue)

So what I did is to make the by-name feature in PR #19 and I added the instructions in the readme in how to enable the feature in case you needed it/wanna fight the class loader

I hope @mockitoguy and I can add the necessary support in `mockito-core` soon so we don't rely on the class loader hack anymore.
