### ISSUE TITLE
can't create mock 

### ISSUE THREAD

**Issue by githorse** [mockito/mockito-scala#65]
Stuck here right out of the gate (using `4.1.0`):

```
package whatever

import org.mockito.MockitoSugar
import org.scalatest.WordSpec

trait Foo {
  def bar: String
  def bar(v: Int): Int
}

class MockSpec extends WordSpec with MockitoSugar {

  val aMock: Foo = mock[Foo]

  "My mock" should {
    "do something useful" in {
      println("look I'm a spec")
    }
  }
}
```

This compiles, but I get an exception when I run the spec:

```
An exception or error caused a run to abort: org.mockito.internal.creation.MockSettingsImpl.build(Ljava/lang/Class;)Lorg/mockito/mock/MockCreationSettings; 
java.lang.NoSuchMethodError: org.mockito.internal.creation.MockSettingsImpl.build(Ljava/lang/Class;)Lorg/mockito/mock/MockCreationSettings;
	at org.mockito.MockitoEnhancer$class.mock(MockitoAPI.scala:198)
	at whatever.MockSpec.mock(MockSpec.scala:11)
	at org.mockito.MockitoEnhancer$class.mock(MockitoAPI.scala:141)
	at whatever.MockSpec.mock(MockSpec.scala:11)
	at whatever.MockSpec.<init>(MockSpec.scala:13)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1422)
	at org.scalatest.tools.Runner$$anonfun$31.apply(Runner.scala:1236)
	at org.scalatest.tools.Runner$$anonfun$31.apply(Runner.scala:1235)
	at scala.collection.immutable.List.map(List.scala:273)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1235)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)```

What am I doing wrong here?

**Comment by ultrasecreth** [comment]
@githorse It seems to me you are pulling an older version of mockito alongside mockito-scala, could you please check that mockito-scala is the only mockito dependency that you have?
If that's already the case, try to get a dependency tree and check if maybe some other library is also bringing mockito.

For reference, mockito-scala already pulls the required version of mockito `"org.mockito" % "mockito-core" % "2.21.0",`, if you see anything different then that's probably your problem.

Please let me know how it went

**Comment by githorse** [comment]
@bbonanno - That's it! I removed my competing `mockito` dependency and all works as advertised. Much obliged :)

**Comment by ultrasecreth** [comment]
@githorse glad to help :)
